const { Activity} = require('../models');

const activityData = [
    {
        activityName: 'Golf',
        address: '75-200 Classic Club Blvd, Palm Desert, CA 92211',
        activityUrl: 'https://www.classicclubgolf.com/',
        category: 'Leisure',
        cost: '18.00',
        activity_date: 'July 30, 2021',
        start_time: new Date(),
        end_time: new Date(),
        tripId: 1,
    },
    {
        activityName: 'French Quarter History and Ghostbuster Tour',
        address: '',
        activityUrl: 'https://frenchquarterhistorytours.com/',
        category: 'Leisure',
        cost: '18.00',
        activity_date: 'July 03, 2021',
        start_time: new Date(),
        end_time: new Date(),
        tripId: 2,
    },
    {
        activityName: 'LACMA',
        address: '5905 Wilshire Blvd, Los Angeles, CA 90036',
        activityUrl: 'https://www.lacma.org/',
        category: 'Sightseeing',
        cost: '18.00',
        activity_date: 'July 30, 2021',
        start_time: new Date(),
        end_time: new Date(),
        tripId: 3,
    },
    {
        activityName: 'Golden Gate Bridge',
        address: '',
        activityUrl: 'https://www.goldengate.org/',
        category: 'Sightseeing',
        cost: '18.00',
        activity_date: 'July 03, 2021',
        start_time: new Date(),
        end_time: new Date(),
        tripId: 4,
    },
    {
        activityName: 'Paddle Boarding',
        address: '1228 W Woodin Ave, Chelan, WA 98816',
        activityUrl: 'http://www.chelanparasail.com/',
        category: 'Leisure',
        cost: '18.00',
        activity_date: 'June 12, 2021',
        start_time: new Date(),
        end_time: new Date(),
        tripId: 5,
    },
    {
        activityName: 'Gyeongbokgung Palace',
        address: '161 Sajik-ro, Sejongno, Jongno-gu, Seoul, South Korea',
        activityUrl: 'https://english.visitkorea.or.kr/enu/ATR/SI_EN_3_1_1_1.jsp?cid=264337',
        category: 'Sightseeing',
        cost: '18.00',
        activity_date: 'December 12, 2021',
        start_time: new Date(),
        end_time: new Date(),
        tripId: 6,
    },
    {
        activityName: 'Hagia Sophia',
        address: ' Sultan Ahmet, Ayasofya Meydanı No:1, 34122 Fatih/İstanbul, Turkey',
        activityUrl: 'https://muze.gen.tr/muze-detay/ayasofya',
        category: 'Sightseeing',
        cost: '18.00',
        activity_date: 'October 17, 2021',
        start_time: new Date(),
        end_time: new Date(),
        tripId: 7,
    },
    {
        activityName: 'Beach Hang',
        address: 'Patong beach Pa Tong, Kathu District, Phuket 83150, Thailand',
        activityUrl: '',
        category: 'Leisure',
        cost: '18.00',
        activity_date: 'September 09, 2021',
        start_time: new Date(),
        end_time: new Date(),
        tripId: 8,
    },
    {
        activityName: `Chef Tanya's Kitchen`,
        description: 'Vegan',
        category: 'Food',
        address: '706 S Eugene Rd Palm Springs, CA 92264',
        activityUrl: 'https://www.yelp.com/biz/chef-tanyas-kitchen-palm-springs',
        cost: '9.99',
        reservation: false,
        activity_date: new Date(),
        start_time: new Date(),
        tripId: 1,
    },
    {
        activityName: 'Cafe Du Monde',
        description: '',
        category: 'Food',
        address: '800 Decatur St French Market New Orleans, LA 70116',
        activityUrl: 'https://www.yelp.com/biz/caf%C3%A9-du-monde-new-orleans-19?osq=cafe+du+monde',
        cost: '9.99',
        reservation: false,
        activity_date: new Date(),
        start_time: new Date(),
        tripId: 2,
    },
    {
        activityName: 'Hayato',
        description: 'Japanese',
        category: 'Food',
        address: '1320 E 7th St Ste 126 Los Angeles, CA 90021',
        activityUrl: 'https://www.yelp.com/biz/hayato-los-angeles-3',
        cost: '9.99',
        reservation: true,
        activity_date: new Date(),
        start_time: new Date(),
        tripId: 3,
    },
    {
        activityName: 'Spruce',
        description: 'American',
        category: 'Food',
        address: '3640 Sacramento St San Francisco, CA 94118',
        activityUrl: 'https://www.yelp.com/biz/spruce-san-francisco',
        cost: '9.99',
        reservation: true,
        activity_date: new Date(),
        start_time: new Date(),
        tripId: 4,
    },
    {
        activityName: 'Local Myth Pizza',
        description: 'Pizza',
        category: 'Food',
        address: '122 S Emerson St Chelan, WA 98816',
        activityUrl: 'https://www.yelp.com/biz/local-myth-pizza-chelan',
        cost: '9.99',
        reservation: false,
        activity_date: new Date(),
        start_time: new Date(),
        tripId: 5,
    },
    {
        activityName: 'Born and Bred',
        description: 'Korean BBQ',
        category: 'Food',
        address: '2F, 1 Majang-ro 42-gil, Seongdong-gu, Seoul, South Korea',
        activityUrl: 'https://guide.michelin.com/en/seoul-capital-area/kr-seoul/restaurant/born-and-bred',
        cost: '9.99',
        reservation: false,
        activity_date: new Date(),
        start_time: new Date(),
        tripId: 6,
    },
    {
        activityName: 'Nicole',
        description: 'Turkish',
        category: 'Food',
        address: 'Tomtom, Tomtom Kaptan Sk. No:18, 34433 Beyoğlu/İstanbul, Turkey',
        activityUrl: 'http://nicole.com.tr/index.php/tr/',
        cost: '9.99',
        reservation: false,
        activity_date: new Date(),
        start_time: new Date(),
        tripId: 7,
    },
    {
        activityName: 'Tumz Seafood Restaurant',
        description: 'Thai',
        category: 'Food',
        address: '63/672, Alley 4, Soi 22 Shops 67,68, 69,70 Wirat Hong Yok 3 Rd, Wichit, Mueang Phuket District, Phuket 83000, Thailand',
        activityUrl: 'https://tumzphuket.com/',
        cost: '9.99',
        reservation: false,
        activity_date: new Date(),
        start_time: new Date(),
        tripId: 8,
    },
    
];

const seedActivity = () => Activity.bulkCreate(activityData);

module.exports = seedActivity;